"""empty message

Revision ID: b5c3041bef18
Revises: de5003d5bb78
Create Date: 2019-03-16 16:51:16.542845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5c3041bef18'
down_revision = 'de5003d5bb78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scans', sa.Column('amount', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scans', 'amount')
    # ### end Alembic commands ###
