"""empty message

Revision ID: de5003d5bb78
Revises: 6895ff5a775e
Create Date: 2019-03-16 16:50:14.832977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de5003d5bb78'
down_revision = '6895ff5a775e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('balance', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'balance')
    # ### end Alembic commands ###
